### ISSUE TITLE
Is there anyway to remove elevation in the bottom bar?

### ISSUE THREAD

**Issue by unamed000** [hacktons/convex_bottom_bar#10]
Hi,

I'm having an issue when using this package
![image](https://user-images.githubusercontent.com/10647722/69037112-d3acd180-0a19-11ea-9de1-4e6b4579a6f4.png)

As you can see, in iphone X it's not working as expected since it's rendering in the SafeArea, but if i put this into a SafeArea layout, there will be a elevation. 

We could work around this one by making the background for this as the same color, but since there are some shadow on it, so it will look weird.

So do we have any way to remove the shadow ?

Thanks

**Comment by avenwu** [comment]
@unamed000 Yes，you can remove the shadow by set elevation to 0.
And you dont have to hack the background to avoid safearea. The latest vesion support iPhoneX safearea internally.

**Comment by unamed000** [comment]
Hi @avenwu.
I used your latest package and it seem working great!

Thanks for your contribution. I appreciate a lot
