### ISSUE TITLE
Detect tab change when swiping to another tab

### ISSUE THREAD

**Issue by kingmaster772** [hacktons/convex_bottom_bar#100]
is there any way to add Listener (TabController) when Swiping to another page with StatelessWidget?
i recently use GetX library to make my page Stateless, but i can't add TabController while it need Stateful

**Comment by avenwu** [comment]
@kingmaster772 https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-change-active-tab-index.md

TabController can be passed in as final argument, you should take care of TabController by yourself, the AppBar don't provide lister for the controller.

And what's are you trying to do with the controller?  Here are some sample code, does it make sense for your case?

```dart
class TheWidget extends StatelessWidget {
  final TabController controller;

  const TheWidget({Key key, this.controller}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return ConvexAppBar(
      controller: controller,
      items: [
        TabItem(title: '2019', icon: Icons.link),
        TabItem(icon: Icons.import_contacts),
        TabItem(title: "2020", icon: Icons.work),
      ],
    );
  }
}
```

**Comment by kingmaster772** [comment]
I want to hide convex_app_bar only if i visit the "+ icon" index (by tapping or swiping), so i can achieve full screen for specific page.

![WhatsApp Image 2020-09-16 at 9 56 57 AM](https://user-images.githubusercontent.com/29949806/93287308-61f11000-f803-11ea-99d9-720617f2344e.jpeg)

**Comment by avenwu** [comment]
As mentions above handle listener with TabController directory. This issue is being closed.
