### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'. issue in convex_botton_bar

### ISSUE THREAD

**Issue by Anishs123** [hacktons/convex_bottom_bar#109]
C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.5.0/lib/src/stack.dart:75:9: Error: The getter 'clipBehavior' isn't defined for the class '_RenderStack'.
 - '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart' ('/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.5.0/lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'.
    if (clipBehavior == Clip.none || size.contains(position)) {
        ^^^^^^^^^^^^

**Comment by avenwu** [comment]
checkout readme or https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-crash-on-flutter-dev-channel.md
