### ISSUE TITLE
Tab selection not registered during tab transition

### ISSUE THREAD

**Issue by Navil** [hacktons/convex_bottom_bar#111]
**Problem**
When tabs are selected too fast (e.g. selecting a tab while another animation is in progress), the new selection is not registered.
The problem also exists when using the demo, but not when using default Flutter tabs. 

**Example**
The issue is shown in following GIF:
![screen-capture](https://user-images.githubusercontent.com/3436399/95634332-f1e44b80-0a89-11eb-9072-240a9084f246.gif)

**Result**
As a result, the NavigationBar shows the wrong Tab to the current page.

**Comment by avenwu** [comment]
@Navil Issue confirmed. The state of current page was not updated while click fast. Update to `2.5.1+1`  should fix this bug.
