### ISSUE TITLE
Setting tab item to accept Text widget

### ISSUE THREAD

**Issue by xapatjb4** [hacktons/convex_bottom_bar#116]
Hello, for the text title, the tab item accepts a String as a title(see link below). Would it be possible to provide a Text widget as an option to pass in?

I wouldn't mind implementing it myself if you one of you can explain the procedure of implementing an enhancement

https://github.com/hacktons/convex_bottom_bar/blob/master/lib/src/item.dart#L22

**Comment by avenwu** [comment]
sadly you can't do that. To custom the tab use the custom constructor of appbar instead.

**Comment by xapatjb4** [comment]
Gotcha, I was looking at the flutter docs for there nav bar items, and they deprecated using a widget as title so you're right. closing issue
