### ISSUE TITLE
Cancel navigation onTap

### ISSUE THREAD

**Issue by mmasdivins** [hacktons/convex_bottom_bar#119]
When changing tab depending on the tab tapped I want to open an input dialog with a request for a password, if the password is correct continue the navigation if not cancel the navigation. Here is a code for the example:

```
ConvexAppBar(
        style: TabStyle.react,
        items: [
          TabItem(icon: Icons.settings),
          TabItem(icon: Icons.fingerprint),
          TabItem(icon: Icons.contacts),
        ],
        initialActiveIndex: 1,//optional, default as 0
        onTap: (int i) async {
          if (i == 0 || i == 2){
            final String pwd = await HelperDialogs.inputDialogasync(context);
            if (pwd == "root") {
              setState(() {
                selectedPage = i;
              });
            } else if (StringUtils.isNotNullOrEmpty(pwd)) {
              snackBarErrorMessage();
            }
          } else{
            setState(() {
              selectedPage = i;
            });
          }

        },
      )
```

The code works perfectly, if I put the wrong password the app stays in the same page, the problem is that the active tab changes,
how can I solve that?

**Comment by avenwu** [comment]
I guess you can do something with 
tap hook, checkout doc here: https://github.com/hacktons/convex_bottom_bar/blob/master/doc/how-to-block-tab-event.md

**Comment by mmasdivins** [comment]
Thanks it worked, but I had to made the TapNotifier return a Future<bool> to be able to await the result from the input dialog.
