### ISSUE TITLE
Rerendering bar after setState()

### ISSUE THREAD

**Issue by moth71** [hacktons/convex_bottom_bar#120]
Hi, i create the bar instance depending on certain BlockState states. It is possible that the bar contains different elements. If so, the widget will not render correctly.

Best greetings.

**Environment details**

[✓] Flutter (Channel stable, 1.20.3, on macOS 11.0.1 20B29, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

• No issues found!

dependencies:
  convex_bottom_bar: ^2.6.0

**To Reproduce**

1. create an bottom bar with  3 Items e.g. var _bottomTabBar = ConvexAppBar(
    items: [
      TabItem(icon: Icons.help),
      TabItem(icon: Icons.help),
      TabItem(icon: Icons.help)
    ],
    style: TabStyle.react,
  );

2. call setState() with new _bottomTabBar instance e.g. 

 setState(() {
     _bottomTabBar = ConvexAppBar(
           items: [
                         TabItem(icon: Icons.call_split),
                         TabItem(icon: Icons.delete_forever),                     
                     ],
           style: TabStyle.react,
  );

![convexBottombar](https://user-images.githubusercontent.com/33552866/99578531-42ca5680-29dd-11eb-855e-da9a74eb26ba.png)

**Comment by avenwu** [comment]
try to add different global key for the appbar

**Comment by moth71** [comment]
thx, it works.
