### ISSUE TITLE
add page transition animation

### ISSUE THREAD

**Issue by jdeltoft** [hacktons/convex_bottom_bar#122]
Not sure how to request a new feature, but wanted to either ask or request a way to change the animation used to go between pages.  I was able to use this help to make my pages which I think you should also add more information about to the readme.

https://codingwithdhrumil.com/2020/10/flutter-convex-bottom-navigation-bar-example.html

I didn't really know how to do this until I saw:

```
  int selectedIndex = 0;
  List<Widget> listWidgets = [Home(),Games(),Apps(),Movies(),Books()];

``` 

and then just using the index to get the page:

`body: listWidgets[selectedIndex],
`

Is there a good way to add more animation between these pages?

**Comment by avenwu** [comment]
The usage of appbar is quite simple, just follow the readme. Or you can refer to the doc here: https://bar.hacktons.cn

As for the page transition, sorry for not providing any instructions. But it actually has nothing to do with appbar. You should checkout flutter api to implement your scaffold widget😅

**Comment by jdeltoft** [comment]
Ok, I'll keep investigating
