### ISSUE TITLE
changing my tab index programatically doesn't update the tab curve bump out

### ISSUE THREAD

**Issue by jdeltoft** [hacktons/convex_bottom_bar#124]
I used provider to change the index of the tab I was on rather than an "onTap" command.  It works, but the convex bottom bar bump tab selection doesn't change even if I call setState()

**Comment by jdeltoft** [comment]
I see there is a function called animateTo() inside class ConvexAppBarState.  Also _onTabClick() but that's private?  Any way I can programatically call animateTo() from my own code?

**Comment by avenwu** [comment]
not for now. The appbar manager index internally, and has not compact with provider. Maybe later as this situation is not a common case.
Would you mind post gist about how you are using appbar with state package?

**Comment by jdeltoft** [comment]
I switched to just use standard bottom tab index.  so if you want to keep open fine, but I found a way to programmatically change that one fine.

**Comment by sawirricardo** [comment]
Hi, I needed this, too. I'm using GetX and on one tab, I want to 
Get.toNamed('/my-page'); so the tab didn't persist.
But, when I get back, the bottom bar still shows on index = n, instead of index = 0
I want to update the bottom bar programmatically

cc @avenwu
