### ISSUE TITLE
changing tabs in a tabbar screen triggers the bottombar tab change

### ISSUE THREAD

**Issue by adnanjpg** [hacktons/convex_bottom_bar#125]
changing tabs in a tabbar screen triggers the bottombar tab change.

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.0)
[✓] Connected device (1 available)

• No issues found!


Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (4 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

```
```
dependencies:
  convex_bottom_bar: ^2.6.0
```

1. initialize the bottom bar 
2. create a screen with a tabbar
3. try to change the tab

![Screenshot_1607702621](https://user-images.githubusercontent.com/54329101/101925995-a2ceaa00-3be3-11eb-84a9-3a4f7214b2ef.png)
![Screenshot_1607702631](https://user-images.githubusercontent.com/54329101/101925999-a4986d80-3be3-11eb-88a1-26c5f049a26f.png)

**Comment by avenwu** [comment]
Are you using default controller? The appbar can bind to controller. Pass a custom one to avoid binding default controller.

**Comment by adnanjpg** [comment]
this solution worked, thank you.
