### ISSUE TITLE
Transparency of ConvexButton

### ISSUE THREAD

**Issue by Akiat** [hacktons/convex_bottom_bar#126]
Thank you for this great package,

I use the `ConvexButton` in my project, I can set the transparency of the bottom bar, but there is still a non-transparent part (which have the same size as the `icon`).

Here is a screenshot of the actual behavior and my code:

```
bottomNavigationBar: ConvexButton.fab(
    icon: Icons.home,
    backgroundColor: THIRD_COLOR.withOpacity(0.5),
    onTap: () => setState(() => Application.router.navigateTo(context, Routes.home)),
    color: Colors.white,
    iconSize: 30,
),
```

![2020-12-14 12_22_40-Android Emulator - Pixel_4_API_30_5554](https://user-images.githubusercontent.com/1292785/102076672-5adc9c80-3e08-11eb-9162-a81f5213de26.png)

Is there a way to avoid this ? Is it the attended behavior or a bug ?

Thanks for your time 👍

**Comment by avenwu** [comment]
Can be a bug😂, I haven't test for transparency. Will have a check later.

**Comment by Akiat** [comment]
Great, thank you :)

**Comment by avenwu** [comment]
@Akiat This bug is caused by `Scaffold.bottomNavigationBar`, which will clip any content reach edge of bottom bar. A workaround is use ConvexButton without bottomNavigationBar. You can place the bar at bottom of `body`.
There is nothing we can do inside the ConvexButton.

**Comment by Akiat** [comment]
Thank you for your debug / answer 👍
