### ISSUE TITLE
Using an image instead of an icon for actionItem 

### ISSUE THREAD

**Issue by cipriancirstea** [hacktons/convex_bottom_bar#13]
Hi. 
Great plugin. Thank you for writing it. Is there a way to use an image instead of an icon for actionItem?

**Comment by avenwu** [comment]
Currently, the internal styles use ICON just for convenient，If you need image instead, try to implement a custom style. 
I will add support for image in next version

**Comment by cipriancirstea** [comment]
Hello. Great to hear. I don't know what you mean by custom style. Do you know any examples?

**Comment by avenwu** [comment]
@cipriancirstea have a look at https://github.com/hacktons/convex_bottom_bar/blob/master/example/lib/custom_appbar_sample.dart
let me know if you have anyother with custom style😉

**Comment by avenwu** [comment]
v1.3.1 has just released., which supports image. You may define the TabItem with `Image Widget` to use images.
```dart
TabItem<Widget>(icon: Image.asset('images/sample.png'), title: 'Discovery')
```

**Comment by cipriancirstea** [comment]
Thank you. For me adding an image will be ideal. Will wait until the next update.

**Comment by avenwu** [comment]
@cipriancirstea the latest version has internal support for image. You dont have to make any customization to use image. Just try v1.3.1+1
