### ISSUE TITLE
New feature: add option for disabled itemTab

### ISSUE THREAD

**Issue by robertoltrocha** [hacktons/convex_bottom_bar#133]
Hi,
is it possible to include an option to disable the itemTab? when onTap nothing happens? and put it in another color? or does this option already exist and I couldn't find it?
thanks

**Comment by avenwu** [comment]
There are some relative features, you may checkout the instruction here:
[How to block tab event?](https://github.com/hacktons/convex_bottom_bar/blob/master/doc/how-to-block-tab-event.md)

If the `block feature` isn't suitable for your case, you can append more details.

**Comment by robertoltrocha** [comment]
Perfect!!!!
thanks
