### ISSUE TITLE
How do i  change TabStyle.FixedCircle position?

### ISSUE THREAD

**Issue by sodipto** [hacktons/convex_bottom_bar#137]
How do i  change **TabStyle.FixedCircle** position? it's always fixed in **center** position. how can i change the position in **right**?

**Comment by avenwu** [comment]
It's fixed center. Why would you like to fix in right?

**Comment by sodipto** [comment]
Design perpus, i would fix in right side. Also always bottom bar items set **odd** number otherwise throw exception. **Ex**: my bottom navbar need 4(Even) items. How i **resolve** this problem?

**Comment by avenwu** [comment]
The bar is based on symmetric design. And fixed style requires num of tabs to be an odd num. The other styles don't  have this constraint.

**Comment by ChauCM** [comment]
@sodipto have you found a way to do this?

**Comment by sodipto** [comment]
> @sodipto have you found a way to do this?

 No. I used custom bottom bottom bar.
