### ISSUE TITLE
losing the state data when moving from screen to screen 

### ISSUE THREAD

**Issue by Wadie-ess** [hacktons/convex_bottom_bar#142]
## Notice for Stack compile error
```
* Replace all Stack.overflow to Stack.clipBehavior. 
* The removal of [Stack.overflow][https://api.flutter.dev/flutter/widgets/Stack/overflow.html] is not a good idea, and the Flutter team has noticed that it would take time to remove all the usage without breaking Google.
Since the overflow has been removed in 1.20 and be rolled back now(perhaps 1.22? not for sure). It's hard to say when it will be removed again, so just replace all overflow with clipBehavior.
```
---

> Please search the [issue list](https://github.com/hacktons/convex_bottom_bar/issues) and [FAQ list](https://github.com/hacktons/convex_bottom_bar#faq) before opening any issues!!

**Describe the bug**

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
flutter --version
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: x.y.z
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by avenwu** [comment]
this issue is fired with meaningless content. also it seems has nothing to do with appbar
