### ISSUE TITLE
Can't set corner radius and curve size at the same time

### ISSUE THREAD

**Issue by dragojsguru** [hacktons/convex_bottom_bar#144]
<img width="586" alt="Screenshot 2021-05-03 at 18 40 01" src="https://user-images.githubusercontent.com/60132060/116905324-1b8bdc80-ac3f-11eb-9a79-ff9785ddfcc6.png">
<img width="201" alt="Screenshot 2021-05-03 at 18 40 31" src="https://user-images.githubusercontent.com/60132060/116905329-1d55a000-ac3f-11eb-876a-b27445eba75a.png">I'm trying to make something like on the first image, but now it's not possible, because if I set curveSize=0 I lose corner radius I don't know why. Can you help me, is this bug, or I make mistake somewhere?

If i set curveSize=0 I get like this
<img width="201" alt="Screenshot 2021-05-03 at 18 45 21" src="https://user-images.githubusercontent.com/60132060/116905772-b84e7a00-ac3f-11eb-985f-399e7b6bb91a.png">

**Comment by avenwu** [comment]
The corner radius will be ignored if there is no curve line. Which means you can't set curveSize to 0 if you need corner.

If you really don't need the curve size, than you can use the official appbar and set the background widget as you wish.
