### ISSUE TITLE
is there a way to change the inactive color in FIxedcircle

### ISSUE THREAD

**Issue by shivpatil007** [hacktons/convex_bottom_bar#145]
## Notice for Stack compile error
```
* Replace all Stack.overflow to Stack.clipBehavior. 
* The removal of [Stack.overflow][https://api.flutter.dev/flutter/widgets/Stack/overflow.html] is not a good idea, and the Flutter team has noticed that it would take time to remove all the usage without breaking Google.
Since the overflow has been removed in 1.20 and be rolled back now(perhaps 1.22? not for sure). It's hard to say when it will be removed again, so just replace all overflow with clipBehavior.
```
---

> Please search the [issue list](https://github.com/hacktons/convex_bottom_bar/issues) and [FAQ list](https://github.com/hacktons/convex_bottom_bar#faq) before opening any issues!!

**Describe the bug**

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
flutter --version
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: x.y.z
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

![Screenshot_2021-05-04-13-18-43-188_com anylopez clinica_any_lopez_mobile](https://user-images.githubusercontent.com/65378260/116974360-ef5f7280-acb5-11eb-8b91-0489346443ce.jpg)

**Comment by avenwu** [comment]
Use the color for normal state,and active Color for selected state.
