### ISSUE TITLE
Item Badges alignment isn't right

### ISSUE THREAD

**Issue by lucianojung** [hacktons/convex_bottom_bar#146]
**Describe the bug**

When I create a ConvexAppBar.badge widget and provide a list of badges they are shown at the center/left bottom of the icon instead of the right upper corner

**Environment details**

Using Flutter 2.3.0-1.0.pre.20 - channel master with Dart version 2.14.0
Using package version 3.0.0

**To Reproduce**

1. Create a stateful widget like shown in this [code snippet](https://github.com/lucianojung/flutter_package_examples/blob/master/lib/packages/convex_bottom_bar/convex_bottom_bar_main.dart)
2. Run with edge and Flutter web emulator
3. if necessary activate tabItem Badges

**Expected behavior**

I expected the badges to be shown in the right upper corner of each icon

**Screenshots**

![image](https://user-images.githubusercontent.com/33691403/121050248-b59ff100-c7b8-11eb-8d80-ab0d985ce047.png)

**Comment by avenwu** [comment]
looks weird. have you checkout the badge sample？

**Comment by lucianojung** [comment]
Yes, I used it like this. I'm not changing any alignment only giving BadgesMap using ConvexAppBar.badges

**Comment by zamberform** [comment]
Same problem.
Can I control the badge padding/size like StyleProvider(Style)?

**Comment by zamberform** [comment]
Oh, it can be.

@lucianojung I think you can use this to adjust somewhere

```
ConvexAppBar.badge(
    {
     // some data
    }
    badgePadding: // EdgeInsets you know
    badgeMargin: // EdgeInsets you know
);

```

**Comment by avenwu** [comment]
Reopen if there's anything we can do
