### ISSUE TITLE
Unable to remove the convex shape

### ISSUE THREAD

**Issue by qwyype** [hacktons/convex_bottom_bar#150]
Everything works great, but there is no way to turn off the convex shape to get the usual bottom bar. Now, if you do not specify style, then the default is TabStyle.reactCircle, which contains the convex shape. It will be great if you add the ability to turn off the convex shape. Thanks.

**Comment by avenwu** [comment]
What do you want exactly, any screenshots? The convex shape can be turn off by `curveSize:0`
