### ISSUE TITLE
Bottom overflow

### ISSUE THREAD

**Issue by bksubhuti** [hacktons/convex_bottom_bar#151]
I'm getting bottom overflow issues with your widget, but not with the standard BottomNavigationBar
so I'm using the standard one.

3 or 4 tabs does not matter.

**Comment by avenwu** [comment]
Could you paste the overflow error log? Let's check out if there's anything we can do

**Comment by bksubhuti** [comment]
I went with bottom navybar and released.. however, I do like your project.  I can swap out the navybar with yours.  I'm using 5 bottom bar items.. how many can yours take?  I'm thinking of having settings as a separate view anyway if it is four.  I had the problem, I think back when I was using only  3 or 4 tabs.
