### ISSUE TITLE
Can't change icon size

### ISSUE THREAD

**Issue by SittiphanSittisak** [hacktons/convex_bottom_bar#156]
I follow guild like:
class Style extends StyleHook {
  @override
  double get activeIconSize => 40;

  @override
  double get activeIconMargin =>10;

  @override
  double get iconSize => 30;

  @override
  TextStyle textStyle(Color color) {
    return TextStyle(
      fontSize: 20,
      color:color,
    );
  }
}

The text font size, activeIconSize, activeIconMargin have changed, but iconSize doesn't change.

**Comment by Marcosmaliki** [comment]
Same, i feel like the icon is too big

**Comment by avenwu** [comment]
@SittiphanSittisak Not all internal styles use the hook style, for example the `TabStyle.reactCiirlce` use default size provided by flutter directly. Which style are used?

**Comment by jvegaseg** [comment]
Same problem, any update?

**Comment by SittiphanSittisak** [comment]
Hi, this style is 'reactCircle'.
This project was deleted, so I'm not sure this problem has been fixed yet.

I will try this again.

**Comment by SittiphanSittisak** [comment]
bug, I don't know how to open this issue again. I will create a new issue.
