### ISSUE TITLE
How to fixed the last item?

### ISSUE THREAD

**Issue by EjazAmir** [hacktons/convex_bottom_bar#157]
Hi, im using this package, i want to achieve this layout, in this the last item is fixedCircle. how can i make this possible with this package
<img width="827" alt="Screenshot 2021-10-21 at 8 23 39 PM" src="https://user-images.githubusercontent.com/25684301/138308926-e61df277-4fd9-419a-8dac-c6708826481d.png">
.

**Comment by avenwu** [comment]
You may make the selected index to a fixed number(eg:4), then block the the animation:
```dart
bottomNavigationBar: ConvexAppBar(
        style: TabStyle.reactCircle,
        items: [
          TabItem(icon: Icons.list),
          TabItem(icon: Icons.calendar_today),
          TabItem(icon: Icons.assessment),
        ],
        initialActiveIndex: 2,
        onTabNotify: (int i) => false,
        onTap: (int i) => print('click index=$i'),
      ),
```
