### ISSUE TITLE
Border Color of bottom nav at selected item's curve does not show the right Color 

### ISSUE THREAD

**Issue by TrungJamin** [hacktons/convex_bottom_bar#158]
I'm using convex bottom bar but when I wrap the convexAppbar with a container to decorate border color for it, but I got this bug, It does not show the curve color above the selected item, pls help me. Thank you for reading <3 
I'm using   convex_bottom_bar: ^3.0.0,  flutter sdk: ">=2.12.0 <3.0.0"

![Screenshot 2021-10-24 101655](https://user-images.githubusercontent.com/68997072/138578927-d03a4500-75f4-4a43-adfe-e67b39c3f9ea.jpg)

Here is my code: 
 Widget buildBottomNav(BuildContext context, TabsRouter tabsRouter) {
    final hideBottomNav = tabsRouter.topMatch.meta['hideBottomNav'] == true;
    return hideBottomNav
        ? SizedBox.shrink()
        : Container(
            decoration: BoxDecoration(
              color: Colors.white,
              border: Border(
                top: BorderSide(color: MyColors.selectiveYellow, width: 3.0),
              ),
            ),
            child: ConvexAppBar(
              backgroundColor: MyColors.blueZodiac,
              initialActiveIndex: tabsRouter.activeIndex,
              onTap: tabsRouter.setActiveIndex,
              style: TabStyle.fixed,
              top: -20,
              items: [
                TabItem(icon: Icons.home, title: "Home"),
                TabItem(icon: Icons.margin_rounded, title: "Home"),
                TabItem(icon: Icons.money, title: "Trade"),
                TabItem(icon: Icons.swap_horiz, title: "Home"),
                TabItem(icon: Icons.wallet_giftcard_sharp, title: "Home"),
              ],
            ),
          );
  }
  
![image](https://user-images.githubusercontent.com/68997072/138578873-42cf8b28-84ed-4faa-9f04-5bcaa0e82b8b.png)

**Comment by avenwu** [comment]
Yes, decoration is not working on the appBar if there's any convex or notch shape.
