### ISSUE TITLE
能不能加个功能点？Can you add a function point?

### ISSUE THREAD

**Issue by pheromone** [hacktons/convex_bottom_bar#161]
能不能加个功能点？让底部的文字一直显示出来。
Can you add a function point? Let the text at the bottom remain visible.
![image](https://user-images.githubusercontent.com/14305431/144156539-4e4f9326-11d8-4548-93ec-b95db6cf6f5d.png)

**Comment by avenwu** [comment]
Consider use `TabStyle.react` or custom a new one
