### ISSUE TITLE
example outdated, doesn't work with Null safety

### ISSUE THREAD

**Issue by thorizer** [hacktons/convex_bottom_bar#162]
cloning the example will result in these errors for sdk 2.12.0

![Code_tNcIOqEi0A](https://user-images.githubusercontent.com/13587810/145570115-aedf8bf0-6ea5-493d-a3e7-28879b856ec6.png)

**Comment by avenwu** [comment]
Can't reproduce

**Comment by thorizer** [comment]
@avenwu did you change dart sdk to 2.12.0 ? 
https://github.com/hacktons/convex_bottom_bar/blob/master/example/pubspec.yaml

**Comment by avenwu** [comment]
Not exactly：
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (6 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

```
