### ISSUE TITLE
README.md中的示例代码与包文件中的代码有出入

### ISSUE THREAD

**Issue by Sleepfist** [hacktons/convex_bottom_bar#167]
[README.md](https://github.com/hacktons/convex_bottom_bar#custom-example)文件里这段代码
```
Scaffold(
  bottomNavigationBar: ConvexAppBar.builder(
    count: 5,
    backgroundColor: Colors.blue,
    style: TabStyle.fixed,
    itemBuilder: Builder(),
  )
);

// user defined class
class Builder extends DelegateBuilder {
  @override
  Widget build(BuildContext context, int index, bool active) {
    return Text('TAB $index');
  }
}
```
ConvexAppBar.builder里面设置了style，但在[bar.dart](https://github.com/hacktons/convex_bottom_bar/blob/master/lib/src/bar.dart#L251)里，ConvexAppBar.builder没有style

所以在照着README.md敲以上部分的代码，Android Studio会给报错：
`The named parameter 'style' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'style'.`

**Comment by avenwu** [comment]
文档标示问题确认存在
