### ISSUE TITLE
Switching to a tab with a difference of more than 1 using TabController

### ISSUE THREAD

**Issue by nezhinskii** [hacktons/convex_bottom_bar#171]
I am using my TabController inside ConvexAppBar and I need to programmatically change the current tab. I found that when switching to more than 1 tab, changes in ConvexAppBar do not occur. As far as I understand, this is due to the following code in the _warpToCurrentIndex() method. But I still don't know how to implement a programmatic transition further than to the next tab.
![image](https://user-images.githubusercontent.com/71719863/166683335-f075b4a6-c3a7-4ca5-929e-c486ddb75585.png)

**Comment by AbdullahAli1993** [comment]
Check this link:
https://bar.hacktons.cn/faq/issue-change-active-tab-index.html#work-with-pageview-tabbarview
