### ISSUE TITLE
Body color covering convex curvex

### ISSUE THREAD

**Issue by Entrebear** [hacktons/convex_bottom_bar#174]
**Describe the bug**

When a color is set for the body it covers the ‘curve’ shape of the bar.

**Environment details**

Paste the flutter environment detail.
```
flutter 3.0.0
```
dependencies:
  convex_bottom_bar: 3.0.0
```


**Expected behavior**

The convex curve should be over the body

**Comment by avenwu** [comment]
This is not a bug. The convex is floating above the "content" widget. Color with alpha make it "transparent". So if you use any color with transparency, they would finally "mixed together".
