### ISSUE TITLE
How to change the font weight of the titles

### ISSUE THREAD

**Issue by bhupalreddykokkanti** [hacktons/convex_bottom_bar#175]
In my case, I need bold titles for the bottom bar tabs. I don't see any option to apply font weight.

**Comment by mohhamad-esmaili** [comment]
I opened a pull request for this problem, if it was ok it will merge #177

**Comment by mohhamad-esmaili** [comment]
I opened a pull request #177 to implement `fontSize` and `fontWeight`, if it was ok it will merge and update soon

**Comment by avenwu** [comment]
https://github.com/hacktons/convex_bottom_bar/pull/177
