### ISSUE TITLE
Custom start index

### ISSUE THREAD

**Issue by smileypop** [hacktons/convex_bottom_bar#26]
Can you please add a config value such as `startIndex` to set the active tab at build time? For example, if I want the center tab active at start, and there are 5 tabs, then `startIndex = 2`.

**Comment by avenwu** [comment]
👌Sounds reasonable, will add such config.

**Comment by avenwu** [comment]
update to v2.0.2
```
initialActiveIndex:2
```

**Comment by smileypop** [comment]
@avenwu It's working! Thanks for the quick turnaround.
