### ISSUE TITLE
how to expand item space?

### ISSUE THREAD

**Issue by marcusvbp** [hacktons/convex_bottom_bar#40]
Hello,

I am using ConvexAppBar.builder and DelegateBuilder to make custom tab items.

I want to make the first item to occupy 2 slots of space, or expand it's width to maximum allowed.

This is my current status:

![image](https://user-images.githubusercontent.com/4376611/76465139-b33bc500-63c4-11ea-8a9d-ddfbaf50f221.png)

and code:

 ```
ConvexAppBar.builder(
        backgroundColor: Colors.grey[900],
        elevation: 0,
        itemBuilder: _CustomBuilder(tabitems),
        count: tabitems.length,
        onTap: (int i) {}
)
```

```
class _CustomBuilder extends DelegateBuilder {
  final List<TabItem> items;
  _CustomBuilder(this.items);

  @override
  Widget build(BuildContext context, int index, bool active) {
    var navigationItem = items[index];
    var activeColor = Color.fromRGBO(246, 172, 42, 1);
    var c = Colors.white;
    var _color = active && index != 0 ? activeColor : c;
    var _icon = active
        ? navigationItem.activeIcon ?? navigationItem.icon
        : navigationItem.icon;

    if (index == 0) {
      return Container(
        width: 200,
        child: Row(
          children: <Widget>[
            Icon(_icon, color: _color, size: 11,),
            SizedBox(width: 5,),
            Text(navigationItem.title, style: TextStyle(color: _color, fontSize: 9, letterSpacing: 2.0))
          ],
        ),
      );
    }

    if (index == 1) {
      return SizedBox(width: 10, child: Container(width: 0, color: Colors.red));
    }

    if (index == items.length ~/ 2) {
      return Container(
        width: 65,
        height: 65,
        margin: EdgeInsets.all(5),
        decoration: BoxDecoration(shape: BoxShape.circle, color: activeColor),
        child: Icon(
          Icons.camera_alt,
          size: 25,
          color: Colors.white
        ),
      );
    }
    
    return Container(
      color: Colors.transparent,
      padding: EdgeInsets.only(bottom: 2),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Icon(_icon, color: _color),
          // Text(navigationItem.title, style: TextStyle(color: _color, fontSize: 10, letterSpacing: 2.0))
        ],
      ),
    );
  }

  @override
  bool fixed() {
    return true;
  }
}
```

**Comment by avenwu** [comment]
@marcusvbp 
> I want to make the first item to occupy 2 slots of space, or expand it's width to maximum allowed.

:sweat_smile: You can not expand tab width. All tabs take the same size constraint. Can you explain why you need to do this? It's hard to image the visual effect.

**Comment by marcusvbp** [comment]
> @marcusvbp
> 
> > I want to make the first item to occupy 2 slots of space, or expand it's width to maximum allowed.
> 
> 😅 You can not expand tab width. All tabs take the same size constraint. Can you explain why you need to do this? It's hard to image the visual effect.

"why"? f***king designers, that's why. 🤣

I need to replicate this layout:
![image](https://user-images.githubusercontent.com/4376611/76511525-0ef06780-6432-11ea-8e56-9b9d3dd75f60.png)

But I have talked to my client and he allowed me to change the layout.

**Comment by avenwu** [comment]
what a genius design😂
