### ISSUE TITLE
徽章位置异常，徽章应该位于图标右上角。

### ISSUE THREAD

**Issue by jijkbird** [hacktons/convex_bottom_bar#42]
The badge position is abnormal. The badge should be in the upper right corner of the icon.

**Comment by jijkbird** [comment]
![11](https://user-images.githubusercontent.com/20245625/76645268-9c979880-6593-11ea-9160-c372b6841370.PNG)

**Comment by avenwu** [comment]
Internal badge style is fixed, you may use chipbuilder to handle customization to satisfy your case
