### ISSUE TITLE
Feature Request: FAB

### ISSUE THREAD

**Issue by stefandevo** [hacktons/convex_bottom_bar#44]
Maybe it would be a nice feature that you could replace the middle button with a FAB.
Or when the middle button could have a special color (fixed).
As you have now the +, this is a specific action you want to perform, and therefore maybe not a specific tab page you want to move to.
I think it would be nice to extend the TabItem properties to have fixed colors. 
Thanks for this great component!

**Comment by avenwu** [comment]
Hi @stefandevo , support of standalone FAB is quite reasonable. In fact this project is original inspired from this case. However I would I'd to make sure there are no misunderstanding. Please have check about the git bellow:
![fab](https://user-images.githubusercontent.com/1622234/79933252-1fa8ea00-8482-11ea-99f6-19bb6e15468d.gif)

In order to make the center tab as FAB style, you can confiture the AppBar with `TabStyle.fixedCircle` and provide the `TabItem` with a FAB as icon;

```dart
ConvexAppBar(
  style: TabStyle.fixedCircle,
  items: [
      TabItem<IconData>(icon: Icons.home, title: 'Home'),
      TabItem<IconData>(icon: Icons.map, title: "Discovery"),
      TabItem<Widget>(
          icon: FloatingActionButton(
            backgroundColor: Colors.purple,
            child: Icon(Icons.add, color: Colors.yellowAccent, size: 45,),
            onPressed: () {
              debugPrint('click fab');
            },), title: ''),
      TabItem<IconData>(icon: Icons.message, title: 'Message'),
      TabItem<IconData>(icon: Icons.people, title: 'Profile'),
    ],
  // other config ...
)
```
Hope this can satisfy your situation 😎

**Comment by stefandevo** [comment]
Wow! Exactly what I wanted. Was not aware of possibility to add a Widget instead of IconData. 
Thx!

**Comment by stefandevo** [comment]
One issue maybe - is it possible to de-activate that last tab-icon. Let me explain, when I tap on the FAB I would like to have NO active tab-icons (so all in inactive state colored). How can this be done?

**Comment by avenwu** [comment]
Short answer: Yes, you can.
In this case do not use the provided FAB, you may need to custom a new one. Since the FAB require a  press callback which will override the TAB event.

**Comment by stefandevo** [comment]
Okay! Clear.

I added:
```
            TabItem<Widget>(
                icon: Container(
                  child: Icon(
                    Icons.add,
                    color: Theme.of(context).bottomAppBarColor,
                    size: 45,
                  ),
                  decoration: BoxDecoration(
                    color: Theme.of(context).primaryColor,
                    shape: BoxShape.circle,
                  ),
                ),
                title: ''),
```
