### ISSUE TITLE
Icon doesn't change color

### ISSUE THREAD

**Issue by William-cpu** [hacktons/convex_bottom_bar#47]
Hi. I've been using your plugin and it's really nice, but I have a small issue. I don't know why the icons don't change color when navigating.

This is how I have it set up:

`_items = [
     TabItem(
        icon: Padding(
          padding: const EdgeInsets.only(top: 8.0),
          child: Icon(
            Icons.bookmark,
          ),
        ),
        title: '',
      ),
]`

`    return ConvexAppBar(
      items: _items,
      style: TabStyle.fixedCircle,
      activeColor: Color(0xff2398C3),
      color: Colors.blueGrey,
      backgroundColor: Colors.white,
      elevation: 1,
      onTap: (int i) {},
    );`

Am I doing something wrong?

**Comment by William-cpu** [comment]
Nevermind ... I figured it out. It seems that adding Padding and Icon(Icons...) shows the icon, but it doesn't show change color. But one thing that I might suggest is that if title is empty, the icons should have a top padding. I don't need to use titles and leaving them empty doesn't look too great. I there a way to add padding without using a builder?

**Comment by avenwu** [comment]
@William-cpu Sadly, the internal style does not provide such configurations. We are trying to keep the API simple, that's why we didn't expose any custom APIs for the TAB itself. 

So are you trying to use the AppBar with only icon displayed, No title at all?
We can hide the Text widget if title is empty, does it make sense for your case?

If you need this `hide feature`, just let me know, I will add it to the next milestone.

**Comment by William-cpu** [comment]
@avenwu Hello. Thank you for your response. It would be a nice feature. Hiding the title.

**Comment by William-cpu** [comment]
Just out of curiosity ... I'm having some color issues :) when navigating to a tab, then leaving it. When the app navigates back to that tab, the initial color is set. I am using Provider to set a state and change color based on that, but I'm sure there is a better way.

**Comment by avenwu** [comment]
Can you provide a video and sample code? It would be helpful. I didn't figure out what's the problem.😂
