### ISSUE TITLE
Style no longer available with ConvexAppBar.builder

### ISSUE THREAD

**Issue by Popovma** [hacktons/convex_bottom_bar#54]
Hello,

Did style get removed from the ConvexAppBar.builder?  I am suddenly seeing issues with style no longer being a named parameter to the builder.

Thank you!

**Comment by avenwu** [comment]
Sorry about the inconvenient😅. The style parameter is useless for ConvexAppBar.builder, so we've removed it since v2.2.0. You can just remove it, and the bar should just work as usual.

**Comment by Popovma** [comment]
Thank you for the response. That worked as described!  I appreciate your help
