### ISSUE TITLE
How to prevent reanimate when pop a pushed page?

### ISSUE THREAD

**Issue by CurrySenpai** [hacktons/convex_bottom_bar#56]
![bottom bar](https://user-images.githubusercontent.com/52869827/83981294-267ca680-a8e2-11ea-9d63-56912589842c.gif)

**Comment by avenwu** [comment]
en... Currently, it would be unable to remove the animation when you route back. Because of the transition between tabs and state management, we can not distinguish when you don't need the animation.

We‘ll however keep work on it, but there's no guarantee.
