### ISSUE TITLE
convex_bottom_bar-2.2.2/lib/src/stack.dart:69:13: Error: No named parameter with the name 'overflow'.

### ISSUE THREAD

**Issue by aseitasi15** [hacktons/convex_bottom_bar#58]
**Describe the bug**
when I try use the convex_bottom_bar-2.2.2, it occurs this error, convex_bottom_bar-2.2.2/lib/src/stack.dart:69:13: Error: No named parameter with the name 'overflow'. 

**To Reproduce**
Just build your example, you can get this error. 

**Screenshots**
![Screen Shot 2020-06-20 at 1 51 11 PM](https://user-images.githubusercontent.com/67206983/85211351-2080bf80-b2fd-11ea-9e47-00573c3882a4.png)

**Comment by avenwu** [comment]
@aseitasi15 The `overflow` is defined by Flutter Framework. I guess you are not using the stable flutter version? Try to provide more environment details：
```
flutter doctor
```
```
flutter --version
```

**Comment by aseitasi15** [comment]
Here you are. 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.14.6 18G5033,
    locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

• No issues found!

Flutter 1.20.0-1.0.pre.132 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 5995661777 (2 days ago) • 2020-06-19 16:15:58 -0700
Engine • revision 676cd566f7
Tools • Dart 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

**Comment by avenwu** [comment]
@aseitasi15 😅Pay attention to the flutter version, you are using the master channel which is not ready for production. Try to switch to a stable channel, the latest version should be 1.17.x
