### ISSUE TITLE
Fail to compile on flutter dev channel

### ISSUE THREAD

**Issue by alextekartik** [hacktons/convex_bottom_bar#63]
Thank you for your plugin!

**Describe the bug**

On flutter dev the following error occurs:
```
../../../../../../../app/flutter/dev/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.2.3/lib/src/stack.dart:69:13: Error: No named parameter with the name 'overflow'.
            overflow: overflow);
```

Indeed RenderStack no longer has a overflow parameter.

**Environment details**

```
flutter --version
Flutter 1.20.0-2.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 15a28159bc (8 days ago) • 2020-06-23 04:52:58 -0700
Engine • revision 91a63d6a44
Tools • Dart 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: 2.2.3
```

**To Reproduce**

1. Switch to flutter dev channel
2. Try to compile any app using convex_bottom_bar
3. Compilation error

**Expected behavior**

It should compile!

Thanks!

**Comment by alextekartik** [comment]
(ok I just see that there was a already a PR)

**Comment by avenwu** [comment]
yep, I would suggest we used stable version to develop flutter app as the dev channel can be
frequently broken. As for the property missing issue, if we receive more issues I would try to provide a beta version to compact with dev channel.

**Comment by alextekartik** [comment]
I understand it is sometimes a pain to follow each new releases and I even think that the flutter team should have deprecate the parameter before removing it. Sometimes stable version is unfortunately not possible (beta needed for the Web and dev needed for Desktop). 

In the mean time I will use the github branch from the PR (but here as well having dependency overrides is also a pain). Thanks!

**Comment by avenwu** [comment]
Copy that. I am also developing with flutter-web enable. I just checkout the flutter with 1.17 tag which makes the channel to unknown, then the flutter tool internal will activate the flutter-web support. The key point is use stable flutter version by hack the channel mechanism😅. Anyway, I will try to release a beta version to support the stack issue. Keep watching on this issue.
```
aven-mac-pro:~ aven$ flutter --version
Flutter 1.17.3 • channel unknown • unknown source
Framework • revision b041144f83 (4 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

**Comment by avenwu** [comment]
@alextekartik New beta version has been shipped to support flutter beta channel（v1.20.x）：v2.2.4-flutter-1.20

**Comment by alextekartik** [comment]
Thanks @avenwu It works. Weird that the this dev version is below the stable version, I had to explicitely set `convex_bottom_bar: 2.2.4-flutter-1.20` which means I will have to change the dependency later, if you bump it to `2.2.5-dev.1`, I could just do `convex_bottom_bar: '>=2.2.5-dev.1'` to test the dev version and be fine in the future (many packages have this, i.e a stable `1.2.3` and a dev `1.2.4-dev.1`)

But well the most important: it works on Linux/Mac desktop!

**Comment by avenwu** [comment]
Yes, I was not using a greater version for the dev channel package. That's because the stable version of AppBar will grow when I add new features. But I am not going to keep the dev channel package updated with each new feature🤣. So leaving the package version lower would help me to avoid mess.
