### ISSUE TITLE
in supported style fixed,The protruding part cannot execute the click event，that means ‘top fileds’ can not execute the click event

### ISSUE THREAD

**Issue by liyang1518** [hacktons/convex_bottom_bar#66]
**Describe the bug**

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
flutter --version
```
E:\FSP\APP\fsp_serve_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

dependencies:
  convex_bottom_bar: 1.1.0
```

**To Reproduce**

in supported style fixed,The protruding part cannot execute the click event，that means ‘top fileds’ can not execute the click event

**Comment by avenwu** [comment]
Try with the latest version, should be v2.2.4

**Comment by liyang1518** [comment]
try with v2.2.4 solved it .close
