### ISSUE TITLE
Convex tab item displays in wrong position when a keyboard covers the app bar

### ISSUE THREAD

**Issue by khoasvn** [hacktons/convex_bottom_bar#67]
**Describe the bug**

The convex item displays in wrong position after a keyboard (when using TextField) covers it.

**Environment details**

```
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)

Flutter 1.19.0-4.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8fe7655ed2 (8 days ago) • 2020-07-01 14:31:18 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)
```

```
dependencies:
  convex_bottom_bar: 2.2.4
```

**To Reproduce**

1. Go to 'ReviewScreen'
2. Click on 'PhoneNumberTextField'
3. Dismiss the keyboard after editting the 'PhoneNumberTextField'

**Screenshots**

![bug](https://user-images.githubusercontent.com/67740741/87062727-a2e30c00-c237-11ea-8f8c-05c650499415.jpg)

**Comment by avenwu** [comment]
looks like the initial index is messed up. please provide the code how you are using the appbar

**Comment by khoaSB** [comment]
HomeSreen (where I've used ConvexAppBar)
[https://gist.github.com/khoaSB/0bf419da6b166af391c3d36b0a077f73](url)

ReviewSubmitButton (the app will navigate back to ContactScreen after user click on the submit button)
[https://gist.github.com/khoaSB/a87ccc567899e96fde7dd532c8631e3c](url)

MenuBloc (the Convex App Bar will be called to change index via bloc events)
[https://gist.github.com/khoaSB/6b573803afbde5f5602f32f20db7a29f](url)

Ps: I have removed unnecessary codes. Thanks for your attention!

**Comment by avenwu** [comment]
The code is quit complicated😂, it's hard to analyze. Can you provide a simplified runnable repo

**Comment by khoaSB** [comment]
I hope it will help -> [convex_bug_demo](https://github.com/khoaSB/convex_bug_demo)

**Comment by avenwu** [comment]
@khoasvn try with v2.2.5

**Comment by khoasvn** [comment]
Hi @avenwu, sorry for bothering you again. I just have discovered another bug with the same behavior.
Please pull this repo: [convex_bug_demo [updated]](https://github.com/khoasvn/convex_bug_demo).
The bug happens when I tried to set the initialActiveIndex.

**Comment by avenwu** [comment]
😅

**Comment by fede1295** [comment]
Hello everyone, this bug isn't fully resolved... i have reproduced it opening the new window over the bottom bar, when i close the window and the bottom bar is visible the index is in wrong position...




![Screenshot from 2020-08-10 12-54-16](https://user-images.githubusercontent.com/56728020/89775766-c46e3680-db08-11ea-8d61-fd548ae8883f.png)




I have reproduced it with different flutter versions: 1.17.5, 1.20.0, 1.20.1 and different widget versions: 2.24, 2.25, 2.25+1, 2.3.0, 2.4.0
