### ISSUE TITLE
中间按钮可以处理点击事件

### ISSUE THREAD

**Issue by lihaotian0607** [hacktons/convex_bottom_bar#68]
如果用`ConvexAppBar.builder` 则无法使用` style: TabStyle.fixedCircle,` 
希望TabItem支持自己处理点击事件!!!

**Comment by avenwu** [comment]
问题是什么？请参照issue模板发问。
1.自定义样式与内置样式互斥。
2.中间tab本身就参加了点击事件

**Comment by lihaotian0607** [comment]
> 问题是什么？请参照issue模板发问。
> 1.自定义样式与内置样式互斥。
> 2.中间tab本身就参加了点击事件

是想中间的按钮点击用路由跳转到其他页面! 其他按钮打开对应的页面

**Comment by avenwu** [comment]
通过tab回调的index做差异化分发。不要自动绑定tabview或pageview

**Comment by lihaotian0607** [comment]
> 通过tab回调的index做差异化分发。不要自动绑定tabview或pageview

目前就这样的,只是觉得这样会有点麻烦,多谢!!!!
