### ISSUE TITLE
Deploying on iPhone X simulator the bottom bar too close to bottom

### ISSUE THREAD

**Issue by sallymariehollywood** [hacktons/convex_bottom_bar#7]
When we deploy to an iPhone that has the notch - the bottom bar is too close to the bottom.

When we then wrap inside a SafeArea - the bottom bar is in the safearea but there is a gap between the bar and the edge of the device .... How to make the convex app bar work correctly on latest iPhones ?

**Comment by therealjohnsummer** [comment]
I have this also - on iOS with the new iPhone - the convex bottom appbar sits right at the bottom and there is no space ... Cannot apply SafeArea as this just shifts the appBar and leaves a large gap ...

**Comment by avenwu** [comment]
@sallymariehollywood  please provide the screenshot and version of you iPhone, Xcode
