### ISSUE TITLE
Using gradient background color for active item

### ISSUE THREAD

**Issue by kingmaster772** [hacktons/convex_bottom_bar#71]
Is there any way to use color gradient for active item?

**Comment by avenwu** [comment]
Set a different icon for active item. [TabItem#activeIcon](https://pub.dev/documentation/convex_bottom_bar/latest/convex_appbar/TabItem/activeIcon.html)

**Comment by avenwu** [comment]
Set a different icon for active item. [TabItem#activeIcon](https://pub.dev/documentation/convex_bottom_bar/latest/convex_appbar/TabItem/activeIcon.html)

**Comment by kingmaster772** [comment]
Actually i need to use gradient background color for active item. I can only found `activeColor` option instead of `activeBackgroundColor`

**Comment by avenwu** [comment]
How about provide some screenshots?

**Comment by kingmaster772** [comment]
Just like this

![image](https://user-images.githubusercontent.com/29949806/87528018-262cb380-c6b7-11ea-9897-7cc037ff116c.png)

**Comment by avenwu** [comment]
As mentioned above, use the TabItem to do the customization. Here is a sample similar to what you need:
Take care of the internal style, you may need to define your own builder if it's not compact with your situation

<img width="305" alt="Screen Shot 2020-07-16 at 10 15 20 AM" src="https://user-images.githubusercontent.com/1622234/87619115-fbda0500-c74d-11ea-8dcf-2d55827e2b11.png">

```dart
StyleProvider(
  style: Style(),
  child: ConvexAppBar(
    style: TabStyle.react,
    items: [
      TabItem(icon: Icons.link),
      TabItem(
          icon: Icons.add,
          isIconBlend: false,
          activeIcon: Container(
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Colors.pink, Colors.blue],
                tileMode: TileMode.repeated,
              ),
              color: Colors.redAccent,
            ),
            child: Icon(Icons.add, color: Colors.white, size: 40),
          )),
      TabItem(icon: Icons.work),
    ],
    color: Colors.black87,
    activeColor: Colors.grey,
    backgroundColor: Colors.white,
  ),
)
class Style extends StyleHook {
  @override
  double get activeIconSize => 60;

  @override
  double get activeIconMargin => 0;

  @override
  double get iconSize => 20;

  @override
  TextStyle textStyle(Color color) {
    return TextStyle(fontSize: 20, color: color);
  }
}
```
