### ISSUE TITLE
ConvexAppBar.badge - Badge Alignment Problems

### ISSUE THREAD

**Issue by LloydRBS** [hacktons/convex_bottom_bar#77]
Good Day
When using the 3 tab bar example provided by your flutter package see snippet below:

ConvexAppBar.badge({0: '99+', 1: Icons.assistant_photo, 2: Colors.redAccent},
  items: [
    TabItem(icon: Icons.home, title: 'Home'),
    TabItem(icon: Icons.map, title: 'Discovery'),
    TabItem(icon: Icons.add, title: 'Add'),
  ],
  onTap: (int i) => print('click index=$i'),
);

The alignment of the badge is off compared to the example demonstrated by the package see screenshot below of code above:
<img width="393" alt="Screenshot 2020-07-31 at 12 52 41" src="https://user-images.githubusercontent.com/69039158/89030183-389e2280-d330-11ea-9477-74bcb38d59c9.png">

The Icons are expected to display as demonstrated in the following image and supposed to be hidden on selected icon as demonstrated by the gif images on the package:
<img width="516" alt="Screenshot 2020-07-31 at 13 18 31" src="https://user-images.githubusercontent.com/69039158/89030286-70a56580-d330-11ea-81ba-9ef604f8ad7c.png">

Additionally the selected circle gets smaller when there is a badge added.

Please can you assist in guiding me on what is wrong or what the problem could be.

Thank you 
Much Appreciated

**Comment by avenwu** [comment]
This bad behavior can be caused by some internal improvements, we will  work on it.

**Comment by avenwu** [comment]
@LloydRBS The alignment issue is because of items count. You have only three tabs, so the badge is not exactly like demo. We have changed the implementation so the badge should work without dependent on tab count. We also provide the margin and padding property for badge api. Try to align the widget where you like:)

**Comment by avenwu** [comment]
Both alignment and icon size has been fixed. You may try with v2.4.1

**Comment by LloydRBS** [comment]
> Both alignment and icon size issues have been fixed. You may try with v2.4.1

Thank you for the speedy response and fix will implement and revert back should I have any other concerns or issues

**Comment by avenwu** [comment]
There shouldn't be. Let me if works for you or not.😅
