### ISSUE TITLE
Crashing at compile

### ISSUE THREAD

**Issue by vadrian89** [hacktons/convex_bottom_bar#78]
**Describe the bug**
Hello, I tried the new version for beta channel but not working and oddly enough it shows v2.3.0?
I have deleted the cache, run flutter clean, run flutter repair still the same thing.
Tried both emulator and web version.

Not compiling: 
```
../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart:69:13: Error: No named parameter with the name 'overflow'.
            overflow: overflow);
            ^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart:73:9: Error: The getter 'overflow' isn't defined for the class '_RenderStack'.
 - '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'overflow'.
    if (overflow == Overflow.visible || size.contains(position)) {
        ^^^^^^^^
Unhandled exception:
NoSuchMethodError: The getter 'fileOffset' was called on null.
Receiver: null
Tried calling: fileOffset

```

**Environment details**

Paste the flutter environment detail.
```
[✓] Flutter (Channel beta, 1.20.0-7.3.pre, on Mac OS X 10.15.4 19E287, locale ro-RO)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)

Flutter 1.20.0-7.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision e606910f28 (3 days ago) • 2020-07-28 16:06:37 -0700
Engine • revision ac95267aef
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: ^2.2.4-flutter-1.20
```

1. flutter run
2. see error

**Comment by avenwu** [comment]
Just checkout the readme doc. Beta channel need a specific package version.

**Comment by vadrian89** [comment]
Hello again, I am using that specific beta package version and it is the same error. 

I even deleted the entire flutter installation, installed flutter again, made a clean project, added convex_bottom_bar: ^2.2.4-flutter-1.20 package, tried compiling and I get the exact same error.

**Comment by crsgit** [comment]
> Hello again, I am using that specific beta package version and it is the same error.
> 
> I even deleted the entire flutter installation, installed flutter again, made a clean project, added convex_bottom_bar: ^2.2.4-flutter-1.20 package, tried compiling and I get the exact same error.

try add   convex_bottom_bar: 2.2.4-flutter-1.20
without "^"
