### ISSUE TITLE
Support flutter v1.20

### ISSUE THREAD

**Issue by RodrigoSMarques** [hacktons/convex_bottom_bar#80]
Are you expected to add support for Flutter v.1.20?

I noticed in a commit that I was preparing the version, but I didn't find any changes made.

Thank you!

**Comment by avenwu** [comment]
Yes. Please checkout the readme doc
. We only keep updates with stable flutter version. As for 1.20 there's a specific beta version which may help your case.

**Comment by RodrigoSMarques** [comment]
Thank You,
Excuse-me. I did not check README.MD
