### ISSUE TITLE
Replacement of overflow in Stack widget with clipbehaviour in Flutter v1.20

### ISSUE THREAD

**Issue by RaashVision** [hacktons/convex_bottom_bar#81]
**Describe the bug**
Hi, first of thanks for this wonderful package! I think this package have problem after update to Flutter 1.20. The Flutter team have replace the overflow with clip behaviour but this package is still using it(https://api.flutter.dev/flutter/widgets/Stack/overflow.html). Below is the error I get
![image](https://user-images.githubusercontent.com/14199227/89487576-725fa500-d7d8-11ea-966f-745db4dfbe9f.png)

**Environment details**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale en-MY)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] VS Code, 64-bit edition (version 1.47.2)
[√] Connected device (1 available)
Paste the package version.
```
dependencies:
convex_bottom_bar: ^2.3.0

**To Reproduce**

Steps to reproduce the behavior:
1. Just update Flutter to latest 1.20 in stable
2. Run the example project


**Expected behavior**
Should works 

Flutter team new annocement for clip behaviour
https://docs.google.com/document/d/1gC5Di4ykTCqupD77PWpy9D8xXo0Ide5CnrH0zzVIhKo/edit#heading=h.pub7jnop54q0

**Comment by RaashVision** [comment]
I have checked the package myself, replace few lines of code of oveflow with clip behaviour and I able to run the code. below is the changes I made.
`@override
  Widget build(BuildContext context) {
    // take care of iPhoneX' safe area at bottom edge
    final additionalBottomPadding =
        math.max(MediaQuery.of(context).padding.bottom, 0.0);
    final convexIndex = isFixed() ? (widget.count ~/ 2) : _currentIndex;
    final active = isFixed() ? convexIndex == _currentIndex : true;

    final height = (widget.height ?? BAR_HEIGHT) + additionalBottomPadding;
    final width = MediaQuery.of(context).size.width;
    var percent = isFixed()
        ? const AlwaysStoppedAnimation<double>(0.5)
        : _animation ?? _initAnimation();
    var factor = 1 / widget.count;
    var textDirection = Directionality.of(context);
    var dx = convexIndex / (widget.count - 1);
    if (textDirection == TextDirection.rtl) {
      dx = 1 - dx;
    }
    var offset = FractionalOffset(widget.count > 1 ? dx : 0.0, 0);
    return extend.Stack(
      **clipBehavior: Clip.none,
      //overflow: Overflow.visible,**
      alignment: Alignment.bottomCenter,
      children: <Widget>[
        Container(
          height: height,
          width: width,
          child: CustomPaint(
            painter: ConvexPainter(
              top: widget.top ?? CURVE_TOP,
              width: widget.curveSize ?? CONVEX_SIZE,
              height: widget.curveSize ?? CONVEX_SIZE,
              color: widget.backgroundColor ?? Colors.blue,
              gradient: widget.gradient,
              sigma: widget.elevation ?? ELEVATION,
              leftPercent: percent,
              textDirection: textDirection,
            ),
          ),
        ),
        _barContent(height, additionalBottomPadding, convexIndex),
        Positioned.fill(
          top: widget.top ?? CURVE_TOP,
          bottom: additionalBottomPadding,
          child: FractionallySizedBox(
              widthFactor: factor,
              alignment: offset,
              child: GestureDetector(
                child: _newTab(convexIndex, active),
                onTap: () => _onTabClick(convexIndex),
              )),
        ),
      ],
    );
  }`

**Comment by avenwu** [comment]
This breaking changes is a known issue. 

---

**Attention**
If you are using flutter dev/beta channel, such as flutter v1.20, there can be compile error. Please use v2.2.4-flutter-1.20

---

Also I noticed that the v1.20 has been release into stable channel. We will merge the fixed branch into master soon

**Comment by RaashVision** [comment]
But this is in Flutter stable channel @avenwu 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.18363.959], locale en-MY)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] VS Code, 64-bit edition (version 1.47.2)
[√] Connected device (1 available)
