### ISSUE TITLE
After upgrading flutter to version 1.20, convex bottom bar doesn't work.

### ISSUE THREAD

**Issue by ZdenekKrcal** [hacktons/convex_bottom_bar#83]
**Describe the bug**

After upgrading flutter to version 1.20, convex bottom bar doesn't work. I can't debug my application. When im starting debug i get this:

../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart:69:13: Error: No named parameter with the name 'overflow'.
            overflow: overflow);

../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart:73:9: Error: The getter 'overflow' isn't defined for the class '_RenderStack'.
 - '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'overflow'.
    if (overflow == Overflow.visible || size.contains(position)) {
 

**Environment details**
I'm using windows 10 pro, 64bit

Paste the flutter environment detail.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.19041.388], locale cs-CZ)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: ^2.3.0
```

**Comment by avenwu** [comment]
It's a breaking change caused by Flutter SDK; Since 1.20 is now in stable channel, we are going to ship new version which will work with flutter 1.20
