### ISSUE TITLE
I get bug when I run example

### ISSUE THREAD

**Issue by hyoukaija** [hacktons/convex_bottom_bar#87]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

../lib/src/stack.dart:42:11: Error: No named parameter with the name 'clipBehavior'.
          clipBehavior: clipBehavior,
          ^^^^^^^^^^^^
../lib/src/stack.dart:52:21: Error: The getter 'clipBehavior' isn't defined for the class 'Stack'.
 - 'Stack' is from 'package:convex_bottom_bar/src/stack.dart' ('../lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'.
      clipBehavior: clipBehavior,
                    ^^^^^^^^^^^^
../lib/src/stack.dart:69:11: Error: No named parameter with the name 'clipBehavior'.
          clipBehavior: clipBehavior,
          ^^^^^^^^^^^^
../lib/src/stack.dart:75:9: Error: The getter 'clipBehavior' isn't defined for the class '_RenderStack'.
 - '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart' ('../lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'.
    if (clipBehavior == Clip.none || size.contains(position)) {
        ^^^^^^^^^^^^
Xcode build done.                                            2.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    error: /Users/fenghai/code/flutter/plugin/bottom_navigation/convex_bottom_bar/example/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
    error: /Users/fenghai/code/flutter/plugin/bottom_navigation/convex_bottom_bar/example/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
    error: /Users/fenghai/code/flutter/plugin/bottom_navigation/convex_bottom_bar/example/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths (in target 'Runner' from project 'Runner')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Comment by avenwu** [comment]
😀Checkout out the FAQ list here:

https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-crash-on-flutter-dev-channel.md
