### ISSUE TITLE
Does it support SVG?

### ISSUE THREAD

**Issue by Dorbmon** [hacktons/convex_bottom_bar#88]
Only IconData and Image?

**Comment by avenwu** [comment]
SVG is not supported internally, the IconData is provided by flutter api, so we support it for convenient. Developers should take responsibility to support any widget they need🤟. In other words, use a widget which supports SVG

**Comment by Dorbmon** [comment]
I have solved it by making my own ImageProvide of SVG.



---Original---

**Comment by avenwu** [comment]
Cool, you can post the provider if you like, it can be useful if anyone has similar case.👏
