### ISSUE TITLE
Badge Alignment issues

### ISSUE THREAD

**Issue by LenvZyl** [hacktons/convex_bottom_bar#89]
Badge is incorrectly aligned 

**Environment details**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

convex_bottom_bar: ^2.4.1

```
ConvexAppBar.badge(
          {1: '10'},
          items: items,
          height: 65,
          style: TabStyle.fixedCircle,
          backgroundColor: Colors.white,
          color: Color(0xFF007AFF).withOpacity(0.64),
          activeColor: Color(0xFF007AFF),
          onTap: (int i) => _selectedTab(i),
        )
```

![Screenshot_1597325427](https://user-images.githubusercontent.com/20842612/90140808-9001b100-dd7a-11ea-9907-c950b619058c.png)

**Comment by avenwu** [comment]
checkout the margin parameter.

**Comment by LenvZyl** [comment]
@avenwu I used 
```
badgePadding: EdgeInsets.fromLTRB(4, 0, 4, 1),
          badgeMargin: EdgeInsets.fromLTRB(
            (mediaQueryData.size.width / 5) / 2,
            0,
            0,
            45,
          ),
```
For a local fix
But would prefer a fix on the plugin side

**Comment by avenwu** [comment]
It's hard to say where the right position should be, since different tab style has different content. So it's better to set the position by users.
