### ISSUE TITLE
how to add custom icons in convex_bottom_bar

### ISSUE THREAD

**Issue by SachinPremkumar** [hacktons/convex_bottom_bar#90]
**Describe the bug**

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
flutter --version
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: x.y.z
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kingmaster772** [comment]
You may refer to this issue #14

**Comment by avenwu** [comment]
What does "custom icons" means?
1. Images like png assets. Just set the tab item with widget, you can use image inside the widget.
2. Custom icon like IconData. That's not a issue relative to the Appbar. Use some .ttf font file

**Comment by SachinPremkumar** [comment]
slow the issue
