### ISSUE TITLE
Stack.dart    clipBehavior is Error

### ISSUE THREAD

**Issue by situxinxin** [hacktons/convex_bottom_bar#92]
Compiler message:
../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-2.4.1/lib/src/stack.dart:43:11: Error: No named parameter with the name 'clipBehavior'.
          clipBehavior: clipBehavior,
          ^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-2.4.1/lib/src/stack.dart:53:21: Error: The getter 'clipBehavior' isn't defined for the class 'Stack'.
 - 'Stack' is from 'package:convex_bottom_bar/src/stack.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-2.4.1/lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'.
      clipBehavior: clipBehavior,
                    ^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-2.4.1/lib/src/stack.dart:70:11: Error: No named parameter with the name 'clipBehavior'.
          clipBehavior: clipBehavior,
          ^^^^^^^^^^^^
../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-2.4.1/lib/src/stack.dart:76:9: Error: The getter 'clipBehavior' isn't defined for the class '_RenderStack'.
 - '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart' ('../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-2.4.1/lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'.
    if (clipBehavior == Clip.none || size.contains(position)) {
        ^^^^^^^^^^^^

**Comment by situxinxin** [comment]
Flutter version : 1.17.5

**Comment by avenwu** [comment]
Checkout readme. You need lower version to work with old flutter version
