### ISSUE TITLE
Delay in convex_bottom_bar/doc/issue-change-active-tab-index.md

### ISSUE THREAD

**Issue by rvk2020** [hacktons/convex_bottom_bar#94]
There is a delay: When using 
  TabBarView(
    controller: _tabController,
    ...
   )
  bottomNavigationBar: ConvexAppBar(controller: _tabController),

Only after the complete tab is loaded the BottomNav is getting updated.
This is easily noticeable even is convex_bottom_bar/doc/tabcontroller_pageview.gif
Is there a way to start the bottom nav animation immediately after the Tab is Swiped?

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.48.1)
[√] Connected device (1 available)

flutter --version
Flutter 1.20.2
```
dependencies:
  convex_bottom_bar: 2.4.1
```

**Comment by avenwu** [comment]
the tab is animated after swipe succeed. not as you wished animate while swiping.😅

**Comment by rvk2020** [comment]
Thanks for your response. 

Please may I know if that is possible in any of the future updates? 

I'll truly be looking forwards to it.

**Comment by avenwu** [comment]
Em, the transition is usually triggered by gesture if you use controller, which means trying to make the appbar behave like tabbar needs lots of work. As the delay is not kind of bug and I didn't see too much benefit we can get.

I'm not going to support this "feature" for the foreseeable future. 🤣

**Comment by rvk2020** [comment]
Cool. No worries.
