### ISSUE TITLE
No named parameter ClipBehaviour 

### ISSUE THREAD

**Issue by Ninad07** [hacktons/convex_bottom_bar#95]
Compiler error: 

F:/Android%20Development/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.4.1/lib/src/stack.dart:42:11: Error: No named parameter with the name 'clipBehavior'.
          clipBehavior: clipBehavior,
          ^^^^^^^^^^^^
/F:/Android%20Development/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.4.1/lib/src/stack.dart:52:21: Error: The getter 'clipBehavior' isn't defined for the class 'Stack'.
 - 'Stack' is from 'package:convex_bottom_bar/src/stack.dart' ('/F:/Android%20Development/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.4.1/lib/src/stack.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clipBehavior'.
      clipBehavior: clipBehavior,

**Comment by avenwu** [comment]
Checkout README or FAQ list here. [issue-crash-on-flutter-dev-channel](https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-crash-on-flutter-dev-channel.md)
