### ISSUE TITLE
Feature request: Don´t change selected state when 'addButton' is clicked

### ISSUE THREAD

**Issue by rainerlonau** [hacktons/convex_bottom_bar#98]
I´m using the ConvexAppBar with TabStyle.fixedCircle. Below should be the relevant code.
![2020-09-11_bottomNavigationBar](https://user-images.githubusercontent.com/20230581/92943947-a96a4b80-f453-11ea-9ecd-f2ec6788c396.JPG)
When I click on the addButton (onTap) the color of the title "Overview" turns white, because the addButton is now the selected button. The icon stays at my primaryColor (purple).

1. I would like to have the text also stay at the primaryColor which stands for selected. (Because after the NewScreen I return to this overview screen)
2. I would like that the addButton doesn´t change the color to the accentColor (purple) and stay as white

```
void _selectPage(int index) {
    setState(() {
      // Add button clicked
      if (index == 1) {
        Navigator.pushNamed(context, NewScreen.routeName);
        // Any other menu item clicked
      } else {
        _selectedPageIndex = index;
      }
    });
  }

bottomNavigationBar: ConvexAppBar(
        key: _appBarKey,
        onTap: _selectPage,
        initialActiveIndex: _selectedPageIndex,
        color: Colors.white,
        activeColor: Theme.of(context).accentColor,
        backgroundColor: Theme.of(context).primaryColor,
        style: TabStyle.fixedCircle,
        items: [
          TabItem(
            icon: Icon(Icons.format_list_bulleted_sharp, color: _tabItemColor(0),
            ),
            title: _screens[0]['title'],
          ),
          TabItem(
            icon: Icon(Icons.add, color: Theme.of(context).primaryColor, size: 40,
            ),
            title: '',
          ),
          TabItem(
            icon: Icon(Icons.star, color: _tabItemColor(2),
            ),
            title: _screens[2]['title'],
          ),
        ],
      )
```

I tried to create a workaround and could solve (2.) with the following code. But it´s not really nice and (1.) still is an issue:

```
void _selectPage(int index) {
    setState(() {
      // Add button clicked
      if (index == _addButtonIndex) {
        // Set _activeColor to white so that the add button doesn´t change the color
        _setTabItemActiveColor(Colors.white);
        // Show TrackingEntryNewScreen
        Navigator.pushNamed(context, TrackingEntryNewScreen.routeName).then(
          (value) {
            // When finished the screen (pop) change the color again
            _setTabItemActiveColor(Theme.of(context).accentColor);
            // Set to previous page, which was before the add button was clicked
            _selectPage(_selectedPageIndex);
          },
        );
        // Any other menu item clicked
      } else {
        _selectedPageIndex = index;
      }
    });
  }
```

**Comment by avenwu** [comment]
@rainerlonau  Sorry I'am confused what exactly you are trying to do. Would provide a video to show how your appBar looks like?

**Comment by rainerlonau** [comment]
Hi @avenwu,
basically what I want is that the middle fixed button ('addEntry') is not highlighted (selected state) when pressed. Because I open a new screen with Navigator.pushNamed where the user can add an entry. When an entry is created, the user comes back to the main overview screen via Navigator.pop. Here the same tab and screen are shown like before the.

When looking at the CustomAppBarDemo screen you have three buttons in the bar: '2019', 'Icons.import_contacts' and '2020'. When clicking on the middle Button, I want to open a new screen and the selected state should not change to the middle button.

I`ll try and see if I can edit the custom_appbar_sample.dart and paste the code, but hope that it´s clear now(?)

**Comment by avenwu** [comment]
Got it. You want the middle button behave like a separated button. Similar as the floating button.

Currently you can not intercept the click event, which means all the buttons behave as a whole body. But you case seems reasonable. We may support this feature later.

**Comment by rainerlonau** [comment]
> Got it. You want the middle button behave like a separated button. Similar as the floating button.

Yes, that´s what I want :-)
Ok, I hope I get updated if this is implemented, when this issue is closed. Thanks for your responsiveness.

**Comment by avenwu** [comment]
@rainerlonau Hi, here are some new feature, have a check if it satisfy your case. 
Read the doc to use the new api: [How to block tab event?](https://github.com/hacktons/convex_bottom_bar/blob/f-support-tab-hook/doc/how-to-block-tab-event.md)
 
```yaml
dependencies:
  convex_bottom_bar:
    git:
      url: https://github.com/hacktons/convex_bottom_bar.git
      ref: f-support-tab-hook
```

**Comment by rainerlonau** [comment]
> @rainerlonau Hi, here are some new feature, have a check if it satisfy your case.
> Read the doc to use the new api: [How to block tab event?](https://github.com/hacktons/convex_bottom_bar/blob/f-support-tab-hook/doc/how-to-block-tab-event.md)
> 
> ```yaml
> dependencies:
>   convex_bottom_bar:
>     git:
>       url: https://github.com/hacktons/convex_bottom_bar.git
>       ref: f-support-tab-hook
> ```

Works like a charm. Thank you so much!

**Comment by avenwu** [comment]
😄 New version has been shipped. You can also switch to v2.5.0 to use the hook api.

**Comment by rainerlonau** [comment]
@avenwu Thanks for the update. Good to know and I adjusted the pubspec.
