### ISSUE TITLE
Any possibility to change activecolor for my icon?

### ISSUE THREAD

**Issue by Naografix** [hacktons/convex_bottom_bar#99]
![image](https://user-images.githubusercontent.com/6979203/92999543-f288d100-f521-11ea-9024-86f82a017530.png)

I'm tyring to change my icon color to white. How can I do that?
And is it possible to add line around the bottombar?

Thank you.

**Comment by kingmaster772** [comment]
You may refer to this issue #55

**Comment by avenwu** [comment]
> I'm tyring to change my icon color to white. How can I do that?

Use use a widget instance as your icon, eg: `TabItem(icon: /*Widget child/*, title: 'Home')`

> And is it possible to add line around the bottombar?

How does it look like? Where exactly is the line, do you mean a border line for the whole AppBar?
